name             'opsworks-postfix-dovecot'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures opsworks-postfix-dovecot'
long_description 'Installs/Configures opsworks-postfix-dovecot'
version          '0.1.0'
