---
driver:
  name: docker
  use_sudo: false

# If you add new platforms below, include them in the .travis.yml file matrix
platforms:
- name: centos-6
- name: debian-7
  run_list: recipe[apt]
- name: debian-8
  run_list: recipe[apt]
- name: ubuntu-14.10
  run_list: recipe[apt]
  driver_config:
    image: ubuntu-upstart:14.10

# Non-official images with systemd
- name: centos-7
  driver_config:
    # https://registry.hub.docker.com/u/milcom/centos7-systemd/dockerfile/
    image: milcom/centos7-systemd
    privileged: true
