---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEY_PAIR'] %>
  security_group_ids: ["sg-88b9cbed"]
  subnet_id: subnet-d2e150a5
  associate_public_ip: true
  interface: dns
  region: ap-northeast-1
  availability_zone: ap-northeast-1a
  require_chef_omnibus: true
  instance_type: 't2.micro'

transport:
  ssh_key: <%= File.expand_path("~/.ssh/#{ENV['AWS_KEY_PAIR']}.pem") %>
  connection_timeout: 60
  connection_retries: 5
  username: ec2-user

block_device_mappings:
  ebs_device_name: '/dev/sda1'
  ebs_volume_size: 4
  ebs_device_name: 'true'

provisioner:
  name: chef_solo

platforms:
  - name: AmazonLinux-201503
    driver:
      image_id: ami-cbf90ecb

suites:
  - name: default
    run_list:
      - recipe[postfix]
    attributes:
      postfix:
        main:
          mydomain: "conversion-up.net"
          myorigin: "conversion-up.net"
          mynetworks:
            - "10.0.0.0/16"
            - "127.0.0.0/8"
          inet_interfaces: "all"